apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricsapi
spec:
  selector:
    matchLabels:
      app: metricsapi
  template:
    metadata:
      labels:
        app: metricsapi
    spec:
      containers:
        - name: metricsapi
          image: shivaspk/metricsapi
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: metricsapi
spec:
  type: NodePort
  selector:
    app: metricsapi
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31900
