kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-sc-example
  labels:
    mydata: pvvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/c/k8sdata"
