apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-example-monitor
  name: prometheus-example-monitor
spec:
  endpoints:
    - interval: 30s
      port: 80-tcp
      scheme: http
  selector:
    matchLabels:
      app: metricsapi
